<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>http://www.viridianpainting.com/</loc>
      <lastmod>2017-03-07</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>http://www.viridianpainting.com/about</loc>
      <lastmod>2017-03-07</lastmod>
      <changefreq>monthly</changefreq>
   </url>
   <url>
      <loc>http://www.viridianpainting.com/gallery</loc>
      <lastmod>2017-03-07</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>http://www.viridianpainting.com/reviews</loc>
      <lastmod>2017-03-07</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>http://www.viridianpainting.com/contact</loc>
      <lastmod>2017-03-07</lastmod>
   </url>
   <url>
      <loc>http://www.viridianpainting.com/services/house_painting</loc>
      <lastmod>2017-03-07</lastmod>
      <changefreq>monthly</changefreq>
   </url>
   <url>
      <loc>http://www.viridianpainting.com/services/furniture_assemblies</loc>
      <lastmod>2017-03-07</lastmod>
      <changefreq>monthly</changefreq>
   </url>
</urlset>